"""Phase 4 inverse: field -> seed points (local SDF maxima) -> watershed
tessellation -> recovered instance labels. Closes the round-trip loop
(labels -> field -> tessellate -> recovered labels) used to validate the
field representation before it's used as a DDIM training target.
"""
import numpy as np
from scipy import ndimage as ndi
from skimage import morphology, segmentation
from skimage.feature import peak_local_max
from skimage.morphology import h_maxima


def tessellate_from_field(field: np.ndarray, peak_h_frac: float = 0.7, peak_min_distance: int = 16,
                           smooth_sigma: float = 6.0) -> np.ndarray:
    """`peak_h_frac` is a *relative* (per-component) h-maxima threshold, not
    an absolute pixel height -- this reintroduced (and now fixes) the exact
    bug Phase 1 found and fixed in classical_watershed.py's segment_classical:
    a single absolute peak_h can't serve both small and large cells at once
    (drops small-cell markers if high enough to suppress noise in large
    ones, over-fragments large cells if low enough to recover small ones).
    It didn't visibly break the original noise-free round-trip test (see
    PLAN.md Phase 4) because a clean, exact SDF has no stain-texture noise
    to create the spurious sub-threshold dips that make the absolute
    threshold fail on real data -- but a field generated by a trained
    model in Phase 5 won't be noise-free, so this needed fixing before that
    point, not after finding it broken there.

    `smooth_sigma`/`peak_min_distance` defaults were empirically tuned (not
    just increased arbitrarily) against `validate_roundtrip.py`'s degraded
    (blur+quantize+noise) round-trip test -- the original defaults
    (2.0/8, tuned only for the noise-free case) badly over-segmented under
    realistic degradation (whole-image cell count +386.7%, see PLAN.md
    Phase 4) because a light Gaussian blur doesn't fully suppress the
    residual per-pixel noise, whose scale is comparable to or larger than a
    small cell's own peak height. Swept smooth_sigma/peak_min_distance
    jointly on the same degraded test until the whole-image cell-count
    error crossed back near 0% (6.0/16 -> +0.6%, vs. +386.7% at the old
    defaults) while checking the noise-free case didn't regress past the
    10% threshold in the process (-5.1% at 6.0/16, was -2.8% -- comfortably
    inside the threshold, a real but small cost for much better degraded-
    case robustness).
    """
    sdf = field[..., 0]
    interior = sdf > 0

    distance_smooth = ndi.gaussian_filter(np.clip(sdf, 0, None), sigma=smooth_sigma)

    labeled_interior, n_interior_comp = ndi.label(interior)
    if n_interior_comp == 0:
        return np.zeros_like(sdf, dtype=np.int32)
    comp_max = ndi.maximum(distance_smooth, labeled_interior, index=np.arange(1, n_interior_comp + 1))
    comp_max_map = np.zeros_like(distance_smooth)
    nonzero = labeled_interior > 0
    comp_max_map[nonzero] = comp_max[labeled_interior[nonzero] - 1]
    normalized_distance = np.zeros_like(distance_smooth)
    normalized_distance[nonzero] = distance_smooth[nonzero] / np.maximum(comp_max_map[nonzero], 1e-6)

    hmax = h_maxima(normalized_distance, h=peak_h_frac)
    coords = peak_local_max(distance_smooth, min_distance=peak_min_distance, labels=interior & (hmax > 0))
    peak_mask = np.zeros_like(sdf, dtype=bool)
    peak_mask[tuple(coords.T)] = True
    markers, _ = ndi.label(peak_mask)

    return segmentation.watershed(-distance_smooth, markers, mask=interior)


if __name__ == "__main__":
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from src.graph.features import extract_cell_features
    from src.graph.field import rasterize_field

    labels = np.load(sys.argv[1])
    node_df = extract_cell_features(labels)
    field = rasterize_field(labels, node_df)
    recovered = tessellate_from_field(field)
    print(f"original: {labels.max()} cells, recovered: {recovered.max()} cells")
